### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jonny-ervine** [frebib/nzbget-exporter#2]
The nzbget-exporter is generating an error when queried:
curl http://nzbget-exporter:9452/metrics
An error has occurred while serving metrics:

GOOD does not belong to DeleteStatus values

Trying to rebuild the exporter with Good being added to DeleteStatus brings a build error:
./collect.go:421:42: hi.ParStatus.String undefined (type ParStatus has no field or method String)
./collect.go:422:48: hi.UnpackStatus.String undefined (type UnpackStatus has no field or method String)

This hasn't changed though, and I get the same build error when trying to build the container image from the source here.

**Comment by frebib** [comment]
According to the documentation, `GOOD` is not a valid value for DeleteStatus. This sounds like an NzbGet bug to me. Is the issue reproducible?

To build you need to run `go generate` first: https://github.com/frebib/nzbget-exporter/blob/master/.drone.yml#L14

I'll push a change to update the documentation to make it more obvious how to build this

**Comment by jonny-ervine** [comment]
Thanks for the quick reply. The issue is reproducible insofar as that my history is returning this value. When I curl against the history API endpoint, then some history DeleteStatus values do have Good as a value. It sounds like NZBget have put this in without updating the API docs. If it helps, I'm running NZBget in a container on Alpine, and it is running 21.1

For the build, that makes sense to have to run go gneerate beforehand - is this not run as part of the container build in the Dockerfile? I'm trying to rebuild the container using the Dockerfile, so I thought that go generate would be run as part of the container build. [I'm using kaniko to build the container image, but have also tested with buildah]
